### ISSUE TITLE
Sparkl for Pentaho 9.0 not available in the Marketplace

### ISSUE THREAD

**Issue by kleysonr** [webdetails/sparkl#89]
Sparkl for Pentaho 9.0 is not available in the https://public.nexus.pentaho.org/ neither Pentaho Marketplace (https://github.com/pentaho/marketplace-metadata/blob/master/marketplace.xml).

Would be possible make it available for public download ?

Best Regards.

**Comment by pamval** [comment]
wget https://public.nexus.pentaho.org/content/groups/omni/org/pentaho/ctools/sparkl/9.0.0.0-423/sparkl-9.0.0.0-423.zip -O sparkl.zip

just because you don't see it doesn't mean it's there :). The public nexus acts as a proxy to the internal one. I'll update the marketplace metadata shortly, but in the meantime you can download from the url above.

**Comment by kleysonr** [comment]
Thanks @pamval 

I tried to search it on the Nexus but it didn't appear in the result.
